### ISSUE TITLE
Output in the same line

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/Data-structure-and-algorithms#1]
- The issues
![issue](https://user-images.githubusercontent.com/88996660/192074467-6b58d913-3027-4902-9549-23c690617789.jpg)

- Expected
Print the output in the different line.
Change the [LinkedLists.java](https://github.com/Tharindu37/Data-structure-and-algorithms/blob/main/Linked%20Lists/LinkedLists.java)

**Comment by CharithaPramod** [comment]
I would like to work on this

**Comment by Tharindu37** [comment]
@CharithaPramod  sure
